
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[426] =
    {   0,
        0,    0,   19,   17,    1,    4,    8,   17,   15,    8,
        8,   17,    7,    8,    8,    8,    7,    8,   14,   14,
        8,    8,    8,    8,    8,    8,    5,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    8,    1,    8,
        0,   10,    0,   15,   15,    0,    0,    0,    0,    0,
       14,    0,    2,   14,   14,    0,    0,   14,    0,   14,
        0,    0,    0,    0,   14,    0,    7,    8,    8,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,    5,
       15,   15,   15,   15,   15,   15,   15,   15,    5,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        6,   15,   15,   15,   15,   15,   15,   15,   10,    0,
       16,   16,   13,   13,   12,   11,    0,    0,    0,    0,
        0,    0,    0,    0,   14,   14,    0,    0,    0,    0,
        2,   14,    0,   14,   14,    0,    0,   14,    0,   14,
        0,   14,   14,   14,    0,   14,   14,    0,   14,    8,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,    5,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   16,    0,    0,    0,   14,    0,
        0,    0,    0,   14,    0,    0,    3,   14,    0,    0,
       14,   14,   14,    0,   14,   14,    0,    0,    0,   14,
       14,    0,    0,   14,    0,   14,    0,    0,    0,   14,
        0,   14,    0,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,    0,   14,    6,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   14,   15,   15,   15,    0,
        0,    0,    0,    0,   16,    0,    0,   14,    0,    0,
        0,   14,    0,    0,    0,    0,    0,   14,    0,    0,
       15,   15,   15,   15,   15,   15,   15,   15,    5,   15,
       15,   15,   15,   15,   15,    0,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        5,   15,   15,    0,   16,    0,   14,   14,    0,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,    0,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        9,    9,   15,   15,   15,   15,   15,    0,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        0,    5,   15,   15,   15,   15,   15,   15,    0,   15,
       15,    6,   15,   15,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   32,   34,   35,   34,
        8,    8,    8,    8,    8,   36,    8,    8,    8,   37,
        8,    8,    8,    8,    8,    8,    8,   38,    8,    8,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,    8,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    1,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    6,    7,    3,    1,    1,
        1,    1,    7,    5,    5,    5,    5,    5,    5,    3,
        3,    3,    3,    6,    3,    3,    3,    7,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[445] =
    {   0,
        0,    0,  561, 1916,   71, 1916,  528,   67,   57,  524,
       72,   76, 1916,  522,   69,   73,   71,   84,   99,  148,
      471,   58,  465,   76, 1916,  461,  104,  140,  153,  149,
       51,  132,  167,   83,  173,   92,  147,  187,  179,  201,
      195,  209,  181,  218,  223,  235,  236,   60,  134, 1916,
       89,  478,  138,  148,    0,  457,  455,  446,  293,  424,
      336,  393,    0,  277,  368,  405,   89, 1916,  312, 1916,
      383,  285,   93,  376,  297,  323, 1916,  365,  126,  307,
      315,  196,  339,  338,  352,  364,  376,  378,  224,  384,
      389,  398,  402,  413,  415,  417,  419,  421,  430,  434,

      438,  446,  457,  458,  462,  474,  478,  480,  466,  479,
      491,  497,  503,  509,  511,  515,  523,  527,  529,  540,
      531,  549,  551,  553,  565,  569,  571,  567,  373,  362,
      358,  150, 1916, 1916, 1916, 1916,  619,  624,  340,  339,
      330,  140,  328,  319,    0, 1916,  633,  638,  309,  198,
        0,  662,  648,    0, 1916,  655,  669,  679,  487,  696,
        0,  670,  714,  705,    0,  713,    0,  731,  740,  266,
      708,  721,  719,  607,  732,  734,  738,  730,  743,  751,
      749,  757,  771,  765,  766,  779,  780,  785,  791,  793,
      802,  804,  815,  817,  813,  826,  832,  831,  840,  848,

      849,  853,  861,  870,  862,  875,  876,  887,  888,  889,
      900,  902,  901,  918,  913,  919,  927,  933,  931,  942,
      951,  947,  946,  962,  275,  211,  370,  598, 1916, 1004,
      231,  169, 1010, 1015,  209,  251, 1916,    0, 1020, 1030,
     1045, 1035, 1916,  891, 1052, 1916, 1060,  294,  360, 1069,
     1916, 1087, 1078,    0, 1096, 1101, 1027,  665,  537, 1106,
     1111,    0, 1130, 1033, 1068, 1110, 1073, 1111, 1115, 1099,
     1127, 1123, 1131, 1074, 1136, 1147, 1145, 1149, 1153, 1158,
     1164, 1162, 1173, 1175,  133, 1177, 1186, 1192, 1198, 1194,
     1200, 1211, 1212, 1213, 1224, 1225, 1226, 1237, 1238, 1243,

     1249, 1255, 1251, 1260, 1269, 1264, 1275, 1286, 1281,  219,
      270,  147,  737,  282, 1316,  341,  170, 1337, 1342,  165,
      418, 1353, 1368,  684,  844,  797, 1383, 1392, 1219, 1296,
     1364, 1360, 1385, 1312, 1376, 1377, 1389, 1393, 1401, 1402,
     1410, 1418, 1416, 1431, 1432,  119, 1436, 1440, 1444, 1448,
     1462, 1464, 1466, 1460, 1478, 1483, 1479, 1487, 1491, 1495,
     1496, 1507, 1508,  423, 1342,  502, 1549, 1012, 1556, 1540,
     1528, 1545, 1544, 1553, 1558, 1564, 1569, 1570, 1578,  114,
     1584, 1582, 1598, 1590, 1606, 1611, 1607, 1612, 1627, 1623,
      537, 1392, 1631, 1644, 1639, 1652, 1656,  102, 1648, 1669,

     1661, 1670, 1675, 1683, 1688, 1689, 1703, 1697, 1701, 1705,
       93, 1916, 1719, 1717, 1718, 1730, 1731, 1744,   84, 1739,
     1752, 1916, 1757, 1756, 1916, 1824, 1829, 1836, 1843, 1848,
     1855, 1862, 1866, 1868, 1873,  110, 1877,  101, 1881, 1888,
     1895, 1902, 1905, 1908
    } ;

static const flex_int16_t yy_def[445] =
    {   0,
      425,    1,  425,  425,  425,  425,  425,  426,  427,  425,
      425,  428,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  427,  427,  427,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,  425,  425,  425,
      426,  429,  429,   29,  430,  425,  425,  425,  425,  425,
      425,  431,  432,  425,  425,  425,  425,  425,  425,  425,
      433,  425,  425,  434,   20,  425,  425,  425,  425,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,  429,  429,
      429,  426,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,   61,  425,  425,  425,  431,  435,
      432,  425,  425,   65,  425,  425,  425,  425,  425,  425,
      436,  437,   65,  425,  438,  439,   75,  425,   75,  425,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,  429,  440,  441,  429,  425,  425,
      425,  425,  425,  425,  442,  435,  425,  152,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  443,  436,  437,
      425,  425,  250,  163,  425,  425,  425,  444,  438,  439,
      260,  169,  425,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,  425,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,  440,
      440,  425,  441,  440,  441,  429,  425,  425,  425,  442,
      435,  425,  425,  443,  443,  425,  425,  425,  444,  444,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,  425,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,  440,  441,  435,  425,  425,  425,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  425,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
      440,  441,   29,   29,   29,   29,   29,  425,   29,   29,

       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
      425,  425,   29,   29,   29,   29,   29,   29,  425,   29,
       29,  425,   29,   29,    0,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425
    } ;

static const flex_int16_t yy_nxt[1989] =
    {   0,
        4,    5,    6,    5,    5,    7,    8,    9,   10,   11,
       12,   13,   13,   14,   15,   13,   16,   17,   18,   19,
       20,   20,   20,   20,   21,   13,   22,   23,   24,   25,
       13,    9,    9,    9,    9,    9,    9,    9,   13,    4,
       13,   26,   27,   28,   29,   30,   31,   32,   33,   34,
        9,   35,    9,   36,   37,   38,   39,   40,    9,   41,
       42,   43,   44,   45,   46,    9,   47,    9,   13,   48,
       13,   25,   49,   52,   49,   49,   55,   55,   55,   55,
       55,   50,   57,   50,   78,   50,   58,   50,   60,   50,
       61,   61,   61,   61,   61,  129,   50,   62,   89,   50,

       50,   50,   63,   50,   79,  258,   53,   90,  158,  158,
       54,   50,  164,  164,  248,   59,   64,   54,   65,   65,
       65,   65,   66,   55,   55,   55,   55,   55,   53,   50,
      422,   67,   68,   69,   70,   49,   71,   49,   49,   98,
      419,   72,   54,   73,  132,   68,   69,   68,  102,   54,
      229,   54,   70,   50,  170,  411,  129,  398,   54,   55,
       55,   55,   55,   55,   74,   64,  380,   75,   75,   75,
       75,   75,   55,   55,   55,   55,   55,   51,  321,  232,
      229,   68,   69,   70,   80,   91,  310,   92,   54,   53,
       76,   54,   85,  346,   68,   69,   68,   93,   54,   86,

       81,   70,   87,  103,   54,   88,   54,   54,   54,   82,
       94,  236,   83,   54,   54,   54,  237,  311,   95,   84,
       96,   99,  321,   97,  317,  311,   54,  100,  101,   54,
      104,  120,   54,   54,  105,   54,  108,  121,   54,   54,
      122,  229,  113,  106,  109,   54,   54,   54,  110,  107,
      312,   54,  173,   54,   54,   54,  114,   54,  312,  115,
      111,   54,   54,  112,  236,   54,  124,   54,   54,  237,
      116,  117,  181,  118,   54,  119,  364,   54,  123,  125,
       54,  225,   54,   54,   54,  126,  127,  128,  311,   54,
       54,   54,   54,   50,   54,   54,  152,  152,  152,  152,

      152,   54,   54,  136,  163,  163,  163,  163,   66,  312,
       68,  153,  137,  137,  137,  138,  167,  167,  167,  167,
      167,  312,  150,   68,  153,   68,  159,   72,  159,  229,
      252,  160,  160,  160,  160,  160,  325,  139,  229,  168,
      229,  140,  169,  169,  169,  169,  169,  225,  141,  229,
      229,  252,  142,  143,  144,  145,  145,  145,  145,  145,
      226,  227,  228,   54,  225,   76,   54,  171,  225,  146,
      147,   54,  314,   54,   54,  172,  315,  326,  148,  225,
      313,   54,  146,  147,  146,   64,  174,  154,  154,  154,
      154,   66,   50,  165,   54,   54,  252,   54,   54,  175,

      161,   68,   69,  155,   54,   54,  150,  178,   54,  316,
      156,   54,  176,  177,   68,   69,   68,  252,   54,  179,
       54,  155,   64,   54,   66,   66,   66,   66,   66,  391,
       54,  366,   54,  180,   54,   54,  237,   54,   68,   69,
       54,   77,   54,   54,   54,   54,  182,  157,   54,  183,
       54,   68,   69,   68,   54,   54,  135,   54,   54,  185,
      184,   54,  312,  186,   54,  134,  187,  133,   54,   54,
      188,   54,   54,  189,   54,   54,   54,   54,   99,   54,
       54,   54,  190,   54,  131,   54,   54,   54,   50,   54,
       54,  191,   50,   54,   54,   77,   54,   54,  192,  193,

       54,  194,   54,  195,   54,   54,  160,  160,  160,  160,
      160,  200,   54,   54,   54,  366,   54,   54,   54,  196,
      237,   54,   54,   54,   54,   54,   99,  199,   54,  197,
       54,  198,   54,   54,   54,   54,   54,   54,  201,   54,
       54,  204,  202,  391,   54,   54,   54,  203,  205,   50,
       54,   50,  208,   54,  326,   50,   54,   54,  210,   54,
      425,  206,   54,   54,  207,   54,  425,  209,   54,   54,
       54,   54,  425,  252,  211,   54,  312,   54,  213,   54,
      212,   54,   54,   54,  214,   54,   54,   54,   54,   54,
       54,  215,  217,   54,  252,   54,   54,   54,  219,  216,

      226,  227,  228,  425,  225,   54,   54,   54,   54,   54,
       54,  218,  121,  425,  224,   99,  220,   54,  221,   54,
      222,   54,  425,   54,   54,   54,   54,   54,   54,  229,
       54,   54,  223,   54,  229,   54,  425,   54,  230,  230,
      230,  230,  425,  231,  231,  231,  231,  233,  425,  233,
      267,  425,  234,  234,  234,  234,  234,  145,  145,  145,
      145,  145,  240,   54,  240,  425,   54,  241,  241,  241,
      241,  241,  425,   54,  154,  154,  154,  154,   66,  425,
      148,  238,  238,  238,  238,  238,  425,  249,   66,   66,
       66,   66,   66,  425,  425,   68,  153,  156,  242,  242,

      425,  252,  425,  425,  239,  251,  252,  330,   68,  153,
       68,  157,  253,  425,  243,  245,  245,  245,  245,  245,
      252,  244,  252,  251,  256,  256,  325,  252,  425,  246,
      259,  425,  243,  254,  254,  254,  254,  425,  247,  310,
      243,  252,  246,  315,  246,  425,  425,  257,  251,  252,
      167,  167,  167,  167,  167,  261,  255,  425,  243,  262,
      262,  262,  262,  262,   54,  425,  251,   54,  265,  264,
      252,  425,  266,  168,   54,   54,  316,   54,   54,   99,
       54,   99,  263,  268,  425,   54,   54,   54,   54,   99,
       54,   54,  272,   54,   54,  425,   54,   54,   54,   54,

       54,  273,   54,  269,   54,   54,  425,   54,   54,   54,
       54,  270,  271,   54,  326,   54,   54,   54,   99,   99,
      425,   54,  274,   54,   54,   54,  275,   54,  277,  425,
       54,   54,   54,  252,  278,   54,   54,   54,   54,   54,
      276,   54,  425,  425,   54,   54,   54,   54,  285,   99,
       54,   54,   54,  425,  252,  279,  425,   54,  280,   54,
       54,   54,  282,   54,  425,  281,   99,  425,   54,   54,
       54,   54,   54,   54,   54,  283,   54,  284,  425,   54,
      425,   54,   54,   54,  286,   54,  325,   54,   54,  425,
       54,   54,   54,  425,  425,  287,   54,   54,   54,   54,

      288,  425,  425,  289,   54,   54,   54,   54,   54,   54,
      242,  242,   54,  425,   54,   54,  290,   54,  294,   54,
       54,   54,  291,  293,  292,  425,   54,   54,   54,   54,
      425,   54,   54,  244,   54,   54,   54,  295,  296,  425,
      297,   54,   54,   54,   54,   54,   54,  298,   54,  301,
      299,  300,  425,   54,   54,   54,   54,   54,   54,   54,
       54,   54,  302,  303,  425,  425,   54,   54,   54,   54,
      425,  425,   54,   99,   54,  304,  425,   54,   54,   54,
      306,  425,  305,   54,   54,   54,   54,   54,   99,   54,
       54,  121,   54,   54,  307,  425,  121,   54,   54,   54,

      308,   54,   54,   54,  425,   54,   54,   54,   54,  425,
       54,  425,   54,   54,  229,  309,  425,   54,   54,  425,
      425,   54,  425,  231,  231,  231,  231,  425,   54,  234,
      234,  234,  234,  234,  318,  318,  318,  318,  318,  238,
      238,  238,  238,  238,  425,  368,  256,  256,  146,  241,
      241,  241,  241,  241,  242,  242,  425,  319,  368,  425,
      368,  146,  239,  146,  322,  322,  322,  322,  322,  257,
      243,  245,  245,  245,  245,  245,  425,  244,   68,  245,
      245,  245,  245,  245,  425,  246,  249,  323,  243,   54,
      425,   68,  331,   68,  247,  425,  425,  425,  246,   54,

      246,  327,  247,  327,  251,  252,  328,  328,  328,  328,
      328,  253,  425,  425,  425,  254,  254,  254,  254,   66,
      256,  256,  251,  259,   54,   99,  252,  332,  425,   54,
       54,  425,   54,  337,   54,  425,  243,  425,  255,   54,
       54,  251,  252,  257,  425,  425,  425,  425,  261,  262,
      262,  262,  262,  262,  243,   54,  425,  333,   54,  251,
       99,   99,  425,  252,  425,   54,   54,   54,  425,   54,
       54,   54,  263,  425,   54,   99,   54,   54,  334,   54,
      425,   54,   54,   54,  336,  335,   54,   54,  425,   54,
       54,  338,   54,   54,  306,   54,  425,   54,  339,  425,

      340,   54,   54,   54,   54,   54,   54,  342,   54,   54,
       99,   54,   54,   54,   54,   54,  425,  341,   54,   54,
       54,  343,  425,   54,   54,  425,  344,  425,   54,   54,
       54,   54,   54,   54,   54,  347,   54,  349,  345,   54,
      425,   54,   54,   54,  425,   54,  121,  350,   54,  348,
       54,   54,   54,   54,   54,  252,   54,   54,   54,   54,
       54,  330,  351,  352,   54,  425,   54,   54,   54,   54,
       54,   54,  353,  356,  425,  354,  252,   54,   54,   54,
       54,   54,   54,   54,  355,   54,  425,  425,  358,  357,
       54,   54,   54,   54,   54,  425,   54,   54,   99,   54,

      359,  360,   54,   54,   54,   54,  425,   54,   99,   54,
       54,   54,  425,  425,   54,   54,   54,   54,  310,   54,
       54,   54,  365,   54,  361,   54,   54,  121,   54,  362,
       54,   54,  425,   99,   54,   54,  363,   54,  330,  425,
       54,   54,   54,  425,  310,   54,  425,   54,  392,  425,
      425,  425,   54,  425,  425,  316,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  425,  372,   54,  425,
      146,   54,  322,  322,  322,  322,  322,  425,   54,  319,
      425,  316,  425,  146,  319,  146,   68,  322,  322,  322,
      322,  322,  425,  425,  310,  323,  425,  425,  392,   68,

      425,   68,  328,  328,  328,  328,  328,  370,  425,  425,
      323,  367,  367,  367,  367,  367,   54,  425,  425,   54,
       54,   99,  425,   54,   99,  368,   54,  425,  371,  373,
       54,  316,   54,   54,  369,   54,   54,  425,  368,  375,
      368,   54,   54,   54,   54,   54,  425,  425,   54,   54,
      374,   54,   54,  425,  376,   54,  377,   54,   54,   54,
       54,   54,  425,  425,  379,  425,   54,   54,   54,   54,
      425,   99,   54,  378,   54,   54,   54,   54,  121,   99,
      425,  425,   54,  425,   54,  381,  425,   54,   54,  425,
       54,   54,   54,  384,  425,   54,   54,   54,   54,   54,

       54,  382,   54,   54,   54,  383,   54,   54,  385,   99,
       54,  425,  121,  425,   54,  425,   54,  425,   54,  386,
       54,   54,   54,   54,   99,   54,   54,  425,   54,  121,
       54,  425,   54,   99,   54,   54,  425,   54,   54,   54,
      425,   99,   54,   54,   54,   54,   54,   54,  387,   54,
       54,   54,   54,   54,  388,   54,   99,   54,  389,  390,
      425,   54,   54,   54,   54,  425,   54,   54,  367,  367,
      367,  367,  367,   54,   54,  367,  367,  367,  367,  367,
      425,  425,  368,   99,   54,  393,  425,   54,  425,  425,
      425,  369,  425,  425,   54,  368,   54,  368,  369,   54,

       54,   54,  425,   54,   54,   99,   54,  394,  425,   54,
       54,   54,   54,  121,   54,  396,  395,   54,   99,   54,
       54,  397,  425,   54,   54,   54,   54,  425,   54,   54,
       99,   99,  425,  425,   54,   54,   54,   54,   54,  425,
       54,   54,  121,   54,   54,  399,   54,  425,   54,   54,
       54,  400,  412,  401,   54,  403,   54,   54,  402,  425,
      425,  425,   54,   54,   54,   54,   54,   54,  404,  425,
       54,   54,   54,   54,  405,  425,  407,   54,   54,   54,
      425,  425,   54,   54,  425,  425,   54,   54,  406,   54,
       54,   99,   99,   54,  408,   54,  425,   54,   54,  409,

       54,  410,  425,   54,   54,   54,  425,   54,   54,  425,
       54,   54,   54,  425,   54,   54,  413,   54,   54,  425,
       54,  121,   54,  425,  425,   54,   54,   54,   54,   54,
      121,   54,   99,  425,   54,   54,   54,  425,  414,   54,
      416,   54,   54,  415,   54,   54,  425,   54,   54,   54,
       99,  425,   99,   54,   54,   54,   54,  418,  417,   54,
       54,   54,   54,   54,   54,   99,  425,   54,  420,   54,
      425,   54,  425,   54,   54,   54,   54,   54,   54,   99,
      425,  425,  425,   54,   54,   54,   54,   54,  425,   54,
       54,   99,   99,  421,  425,   54,   54,   54,   54,  121,

       54,  425,   99,   54,  424,   54,  423,  425,   54,  425,
       54,   54,   54,   54,  425,   54,   54,  425,   54,  425,
      425,  425,   54,   54,   51,  425,   51,   51,   51,   51,
       51,   54,  425,   54,   54,   54,   56,  425,   56,   56,
       56,   56,   56,  130,  425,  130,  130,  130,  130,  130,
       55,  425,   55,   55,   55,  149,  149,  149,  149,  149,
      149,  149,  151,  425,  151,  151,  151,  151,  151,  162,
      162,  166,  166,  235,  235,  235,  235,  235,  235,  235,
      250,  250,  250,  250,  260,  260,  260,  260,  310,  310,
      310,  310,  310,  310,  310,  313,  313,  313,  313,  313,

      313,  313,  320,  320,  320,  320,  320,  320,  320,  324,
      425,  324,  329,  425,  329,    3,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425
    } ;

static const flex_int16_t yy_chk[1989] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    8,    5,    5,    9,    9,    9,    9,
        9,   11,   12,   15,   22,   22,   12,   48,   17,   16,
       17,   17,   17,   17,   17,   51,   15,   18,   31,   11,

       16,   16,   18,   24,   24,  438,    8,   31,   67,   67,
       31,   18,   73,   73,  436,   12,   19,   31,   19,   19,
       19,   19,   19,   27,   27,   27,   27,   27,   51,   48,
      419,   19,   19,   19,   19,   49,   19,   49,   49,   34,
      411,   19,   34,   19,   53,   19,   19,   19,   36,   34,
      142,   36,   19,   79,   79,  398,  132,  380,   36,   28,
       28,   28,   28,   28,   19,   20,  346,   20,   20,   20,
       20,   20,   29,   29,   29,   29,   29,   53,  320,  142,
      317,   20,   20,   20,   28,   32,  312,   32,   32,  132,
       20,   32,   30,  285,   20,   20,   20,   32,   32,   30,

       28,   20,   30,   37,   54,   30,   37,   54,   30,   29,
       33,  150,   29,   37,   54,   30,  150,  226,   33,   29,
       33,   35,  235,   33,  232,  310,   33,   35,   35,   35,
       38,   43,   35,   33,   38,   39,   39,   43,   39,   35,
       43,  231,   41,   38,   40,   39,   38,   43,   40,   38,
      226,   41,   82,   38,   41,   82,   42,   40,  310,   42,
       40,   41,   82,   40,  236,   42,   45,   40,   42,  236,
       42,   42,   89,   42,   44,   42,  311,   44,   44,   45,
       89,  225,   45,   89,   44,   46,   46,   47,  314,   45,
       89,   46,   47,  170,   46,   47,   64,   64,   64,   64,

       64,   46,   47,   59,   72,   72,   72,   72,   72,  311,
       64,   64,   59,   59,   59,   59,   75,   75,   75,   75,
       75,  314,  149,   64,   64,   64,   69,   72,   69,  144,
      248,   69,   69,   69,   69,   69,  248,   59,  143,   75,
      141,   59,   76,   76,   76,   76,   76,  316,   59,  140,
      139,  248,   59,   59,   59,   61,   61,   61,   61,   61,
      131,  131,  131,   80,  131,   76,   80,   80,  130,   61,
       61,   81,  227,   80,   81,   81,  227,  249,   61,  129,
      316,   81,   61,   61,   61,   65,   83,   65,   65,   65,
       65,   65,   78,   74,   84,   83,  249,   84,   83,   84,

       71,   65,   65,   65,   84,   83,   62,   86,   85,  227,
       65,   85,   85,   85,   65,   65,   65,  249,   85,   87,
       86,   65,   66,   86,   66,   66,   66,   66,   66,  364,
       86,  321,   87,   88,   88,   87,  321,   88,   66,   66,
       90,   60,   87,   90,   88,   91,   90,   66,   91,   91,
       90,   66,   66,   66,   92,   91,   58,   92,   93,   93,
       92,   93,  364,   93,   92,   57,   94,   56,   93,   94,
       95,   95,   94,   96,   95,   97,   96,   98,   97,   94,
       98,   95,   98,   96,   52,   97,   99,   98,   26,   99,
      100,  100,   23,  100,  101,   21,   99,  101,  101,  101,

      100,  102,  102,  103,  101,  102,  159,  159,  159,  159,
      159,  109,  102,  103,  104,  366,  103,  104,  105,  104,
      366,  105,  109,  103,  104,  109,  105,  108,  105,  106,
      106,  107,  109,  106,  107,  110,  108,  107,  110,  108,
      106,  112,  111,  391,  107,  110,  108,  111,  113,   14,
      111,   10,  114,  112,  259,    7,  112,  111,  116,  113,
        3,  113,  113,  112,  113,  114,    0,  115,  114,  113,
      115,  116,    0,  259,  116,  114,  391,  115,  118,  117,
      117,  116,  117,  118,  119,  119,  118,  121,  119,  117,
      121,  120,  122,  118,  259,  119,  120,  121,  123,  120,

      228,  228,  228,    0,  228,  122,  120,  123,  122,  124,
      123,  122,  124,    0,  128,  122,  125,  123,  125,  124,
      126,  125,    0,  128,  125,  126,  128,  127,  126,  137,
      127,  125,  127,  128,  138,  126,    0,  127,  137,  137,
      137,  137,    0,  138,  138,  138,  138,  147,    0,  147,
      174,    0,  147,  147,  147,  147,  147,  148,  148,  148,
      148,  148,  153,  174,  153,    0,  174,  153,  153,  153,
      153,  153,    0,  174,  156,  156,  156,  156,  156,    0,
      148,  152,  152,  152,  152,  152,    0,  162,  157,  157,
      157,  157,  157,    0,    0,  152,  152,  156,  158,  158,

        0,  258,    0,    0,  152,  162,  162,  258,  152,  152,
      152,  157,  162,    0,  158,  160,  160,  160,  160,  160,
      324,  158,  258,  162,  164,  164,  324,  162,    0,  160,
      166,    0,  158,  163,  163,  163,  163,    0,  160,  313,
      164,  324,  160,  313,  160,    0,    0,  164,  166,  166,
      168,  168,  168,  168,  168,  166,  163,    0,  164,  169,
      169,  169,  169,  169,  171,    0,  166,  171,  172,  171,
      166,    0,  173,  168,  171,  173,  313,  172,  173,  175,
      172,  176,  169,  177,    0,  173,  178,  172,  175,  178,
      176,  175,  181,  176,  177,    0,  178,  177,  175,  179,

      176,  182,  179,  179,  177,  181,    0,  180,  181,  179,
      180,  180,  180,  182,  326,  181,  182,  180,  183,  184,
        0,  184,  185,  182,  184,  185,  186,  183,  188,    0,
      183,  184,  185,  326,  189,  186,  187,  183,  186,  187,
      187,  188,    0,    0,  188,  186,  187,  189,  197,  190,
      189,  188,  190,    0,  326,  191,    0,  189,  191,  190,
      192,  191,  193,  192,    0,  192,  194,    0,  191,  195,
      192,  193,  195,  194,  193,  195,  194,  196,    0,  195,
      325,  193,  196,  194,  198,  196,  325,  198,  197,    0,
      198,  197,  196,    0,    0,  199,  199,  198,  197,  199,

      200,  325,    0,  201,  200,  201,  199,  200,  201,  202,
      244,  244,  202,    0,  200,  201,  202,  203,  205,  202,
      203,  205,  203,  204,  203,    0,  204,  203,  205,  204,
        0,  206,  207,  244,  206,  207,  204,  206,  207,    0,
      208,  206,  207,  208,  209,  210,  208,  209,  210,  212,
      210,  211,    0,  208,  209,  210,  211,  213,  212,  211,
      213,  212,  213,  214,    0,    0,  211,  213,  212,  215,
        0,    0,  215,  215,  214,  216,    0,  214,  216,  215,
      218,    0,  217,  217,  214,  216,  217,  219,  220,  218,
      219,  219,  218,  217,  221,    0,  223,  219,  220,  218,

      222,  220,  223,  222,    0,  223,  222,  221,  220,    0,
      221,    0,  223,  222,  230,  224,    0,  221,  224,    0,
        0,  224,    0,  230,  230,  230,  230,    0,  224,  233,
      233,  233,  233,  233,  234,  234,  234,  234,  234,  239,
      239,  239,  239,  239,    0,  368,  257,  257,  234,  240,
      240,  240,  240,  240,  242,  242,    0,  234,  368,    0,
      368,  234,  239,  234,  241,  241,  241,  241,  241,  257,
      242,  245,  245,  245,  245,  245,    0,  242,  241,  247,
      247,  247,  247,  247,    0,  245,  250,  241,  242,  264,
        0,  241,  264,  241,  245,  253,    0,    0,  245,  264,

      245,  252,  247,  252,  250,  250,  252,  252,  252,  252,
      252,  250,    0,  253,  253,  255,  255,  255,  255,  255,
      256,  256,  250,  260,  265,  267,  250,  265,  261,  267,
      274,  253,  267,  274,  265,  253,  256,    0,  255,  267,
      274,  260,  260,  256,    0,    0,  261,  261,  260,  263,
      263,  263,  263,  263,  256,  270,    0,  266,  270,  260,
      270,  268,    0,  260,  261,  270,  266,  268,  261,  266,
      268,  269,  263,    0,  269,  269,  266,  268,  271,  272,
        0,  269,  272,  271,  273,  272,  271,  273,    0,  272,
      273,  275,  275,  271,  276,  275,    0,  273,  277,    0,

      279,  277,  275,  276,  277,  278,  276,  281,  278,  279,
      278,  277,  279,  276,  280,  278,    0,  280,  282,  279,
      281,  282,    0,  281,  280,    0,  283,    0,  282,  283,
      281,  284,  283,  286,  284,  288,  286,  290,  284,  283,
        0,  284,  287,  286,    0,  287,  287,  291,  288,  289,
      290,  288,  287,  290,  289,  329,  291,  289,  288,  291,
      290,  329,  292,  293,  289,    0,  291,  292,  293,  294,
      292,  293,  294,  297,    0,  295,  329,  292,  293,  294,
      295,  296,  297,  295,  296,  297,    0,    0,  300,  299,
      295,  296,  297,  298,  299,    0,  298,  299,  298,  300,

      302,  303,  300,  298,  299,  301,    0,  303,  301,  300,
      303,  302,    0,    0,  302,  301,  304,  303,  315,  304,
      306,  302,  315,  306,  304,  305,  304,  309,  305,  305,
      306,  307,  330,  308,  307,  305,  307,  309,  330,    0,
      309,  307,  308,    0,  365,  308,    0,  309,  365,    0,
        0,    0,  308,  330,    0,  315,  318,  318,  318,  318,
      318,  319,  319,  319,  319,  319,    0,  334,  334,    0,
      318,  334,  322,  322,  322,  322,  322,    0,  334,  318,
        0,  365,    0,  318,  319,  318,  322,  323,  323,  323,
      323,  323,    0,    0,  392,  322,    0,    0,  392,  322,

        0,  322,  327,  327,  327,  327,  327,  331,    0,    0,
      323,  328,  328,  328,  328,  328,  332,    0,    0,  332,
      331,  332,    0,  331,  336,  328,  332,    0,  333,  335,
      331,  392,  335,  336,  328,  335,  336,    0,  328,  338,
      328,  333,  335,  336,  333,  337,    0,    0,  337,  338,
      337,  333,  338,    0,  339,  337,  340,  339,  340,  338,
      339,  340,    0,    0,  343,    0,  341,  339,  340,  341,
        0,  341,  343,  342,  342,  343,  341,  342,  344,  345,
        0,    0,  343,    0,  342,  347,    0,  344,  345,    0,
      344,  345,  347,  350,    0,  347,  348,  344,  345,  348,

      349,  348,  347,  349,  350,  349,  348,  350,  351,  352,
      349,    0,  353,    0,  350,    0,  354,    0,  351,  354,
      352,  351,  353,  352,  357,  353,  354,    0,  351,  356,
      352,    0,  353,  355,  355,  357,    0,  355,  357,  356,
        0,  359,  356,  358,  355,  357,  358,  359,  358,  356,
      359,  360,  361,  358,  360,  361,  361,  359,  362,  363,
        0,  360,  361,  362,  363,    0,  362,  363,  367,  367,
      367,  367,  367,  362,  363,  369,  369,  369,  369,  369,
        0,    0,  367,  371,  371,  370,    0,  371,    0,    0,
        0,  367,    0,    0,  371,  367,  370,  367,  369,  370,

      373,  372,    0,  373,  372,  373,  370,  372,    0,  374,
      373,  372,  374,  374,  375,  378,  377,  375,  375,  374,
      376,  379,    0,  376,  375,  377,  378,    0,  377,  378,
      376,  381,    0,    0,  379,  377,  378,  379,  382,    0,
      381,  382,  382,  381,  379,  383,  384,    0,  382,  384,
      381,  384,  399,  385,  383,  387,  384,  383,  386,    0,
        0,    0,  385,  387,  383,  385,  387,  386,  388,    0,
      386,  388,  385,  387,  389,    0,  390,  386,  388,  390,
        0,    0,  390,  389,    0,    0,  389,  393,  389,  390,
      393,  394,  393,  389,  395,  395,    0,  393,  395,  396,

      394,  397,    0,  394,  399,  395,    0,  399,  396,    0,
      394,  396,  397,    0,  399,  397,  400,  401,  396,    0,
      401,  401,  397,    0,    0,  400,  402,  401,  400,  402,
      402,  403,  403,    0,  403,  400,  402,    0,  404,  404,
      406,  403,  404,  405,  405,  406,    0,  405,  406,  404,
      407,    0,  410,  408,  405,  406,  408,  409,  408,  407,
      409,  410,  407,  408,  410,  413,    0,  409,  414,  407,
        0,  410,    0,  414,  415,  413,  414,  415,  413,  415,
        0,    0,    0,  414,  415,  413,  416,  417,    0,  416,
      417,  417,  418,  416,    0,  420,  416,  417,  420,  421,

      418,    0,  424,  418,  423,  420,  420,    0,  421,    0,
      418,  421,  424,  423,    0,  424,  423,    0,  421,    0,
        0,    0,  424,  423,  426,    0,  426,  426,  426,  426,
      426,  427,    0,  427,  427,  427,  428,    0,  428,  428,
      428,  428,  428,  429,    0,  429,  429,  429,  429,  429,
      430,    0,  430,  430,  430,  431,  431,  431,  431,  431,
      431,  431,  432,    0,  432,  432,  432,  432,  432,  433,
      433,  434,  434,  435,  435,  435,  435,  435,  435,  435,
      437,  437,  437,  437,  439,  439,  439,  439,  440,  440,
      440,  440,  440,  440,  440,  441,  441,  441,  441,  441,

      441,  441,  442,  442,  442,  442,  442,  442,  442,  443,
        0,  443,  444,    0,  444,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[19] =
    {   0,
0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
    #include<bits/stdc++.h>
  
    #include "parser.tab.h"
  #include<string.h>
  using namespace std;
  extern "C" {
        int yylex(void);
    }
    template <typename T>
    T parser_number(string numstr){
        stringstream ss;
        ss << numstr;
        T result(0);
        ss >> result;
        return result;
    }
    unordered_map<string,string > mp1;
    unordered_map<string,int > mp2;
    int linenum=0;
    std::ofstream myfile;
    vector<string>v;
    //
#line 1074 "lex.yy.c"
#line 1075 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 84 "lexer.l"


#line 1295 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 426 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1916 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 86 "lexer.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 88 "lexer.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 90 "lexer.l"
{}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 92 "lexer.l"
{linenum++;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 94 "lexer.l"
{
    mp1[yytext]="Keyword"; mp2[yytext]++; if(mp2[yytext]!=1){} else v.push_back(yytext);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "lexer.l"
{
    mp1[yytext]="Keyword"; mp2[yytext]++; if(mp2[yytext]!=1){} else v.push_back(yytext);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 101 "lexer.l"
{mp1[yytext]="Separator"; mp2[yytext]++; if(mp2[yytext]!=1){} else v.push_back(yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "lexer.l"
{
    mp1[yytext]="Operator"; mp2[yytext]++; if(mp2[yytext]!=1){} else v.push_back(yytext);
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 107 "lexer.l"
{mp1[yytext]="Literal";mp2[yytext]++;if(mp2[yytext]!=1){} else v.push_back(yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 110 "lexer.l"
{

    mp1[yytext]="Literal";
    mp2[yytext]++; 
    if(mp2[yytext]!=1){} else v.push_back(yytext);

}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 119 "lexer.l"
{cout<<yytext<<" "<<" Line number is "<<yylineno<< " Illegal Character is "<<yytext[0]<<endl; mp1[yytext]="Illegal";mp2[yytext]++;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 121 "lexer.l"
{cout<<yytext<<" "<<" Line number is "<<yylineno<< " Illegal Character is "<<yytext[1]<<endl; mp1[yytext]="Illegal";mp2[yytext]++;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 122 "lexer.l"
{

    mp1[yytext]="Literal";
    mp2[yytext]++; 
    if(mp2[yytext]!=1){} else v.push_back(yytext);

}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 131 "lexer.l"
{mp1[yytext]="Literal";mp2[yytext]++;if(mp2[yytext]!=1){} else v.push_back(yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 "lexer.l"
{mp1[yytext]="Identifier";mp2[yytext]++;if(mp2[yytext]!=1){} else v.push_back(yytext); yylval.str = strdup(yytext) ;return IDENTIFIER;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "lexer.l"
{ cout<<yytext<<" "<<" Line number is "<<yylineno<< " Illegal Character is "<<yytext[0]<<endl; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 136 "lexer.l"
{cout<<yytext<<" "<<" Line number is "<<yylineno<< " Illegal Character is "<<yytext[0]<<endl; mp1[yytext]="Illegal";mp2[yytext]++;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 138 "lexer.l"
ECHO;
	YY_BREAK
#line 1473 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 426 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 426 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 425);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 138 "lexer.l"



// int main(int argc, char **argv ){

    
//     ++argv;
//     --argc; 
//     if (argc > 0)yyin = fopen( argv[0], "r" );
//     else yyin = stdin;
//     yylex();
//     myfile.open ("example.csv");
//     myfile<<"Lexeme,Token,Count"<<endl;
//     cout<<"#####STATS#####"<<endl;
//     cout<<"Lexeme,Token,Count"<<endl;
//     for(auto x:v){
//        cout<<x<<","<<mp1[x]<<","<<mp2[x]<<endl;
//         myfile<<x<<","<<mp1[x]<<","<<mp2[x]<<endl;
//     }

//     myfile.close();

// return 0;
// }

